"""French and Brazilian Portuguese labels for the Flora & Fauna section (Oct 2026).

Hand-written (never machine-filled), keyed by the English text of each L(...) label
in flora_fauna_taxa.py / flora_fauna_pages.py. L() looks the English up here and adds
"fr" / "pt"; a label missing from this table shows in English on /fr/ and /pt/.
When you add or reword an English label, add its fr/pt line here too.
French typography: a no-break space ( ) before ":" ";" "?" "!".
"""

FRPT = {
    # realms / IUCN / local languages
    "Animals": ("Animaux", "Animais"),
    "Plants": ("Plantes", "Plantas"),
    "Fungi": ("Champignons", "Fungos"),
    "Least Concern": ("Préoccupation mineure", "Pouco preocupante"),
    "Near Threatened": ("Quasi menacé", "Quase ameaçada"),
    "Vulnerable": ("Vulnérable", "Vulnerável"),
    "Endangered": ("En danger", "Em perigo"),
    "Critically Endangered": ("En danger critique", "Criticamente em perigo"),
    "Extinct in the Wild": ("Éteint à l'état sauvage", "Extinta na natureza"),
    "Extinct": ("Éteint", "Extinta"),
    "Data Deficient": ("Données insuffisantes", "Dados insuficientes"),
    "Sranan Tongo": ("sranan tongo", "sranan tongo"),
    "Surinamese Dutch": ("néerlandais du Suriname", "neerlandês do Suriname"),
    # groups + intros
    "Mammals": ("Mammifères", "Mamíferos"),
    "Monkeys, big cats, sloths, bats, manatees and every other mammal recorded in Suriname.":
        ("Singes, grands félins, paresseux, chauves-souris, lamantins et tous les autres mammifères observés au Suriname.",
         "Macacos, grandes felinos, preguiças, morcegos, peixes-boi e todos os outros mamíferos registrados no Suriname."),
    "Birds": ("Oiseaux", "Aves"),
    "From the great kiskadee in every Paramaribo garden to harpy eagles and cock-of-the-rocks deep in the interior.":
        ("Du tyran quiquivi, présent dans chaque jardin de Paramaribo, à la harpie féroce et au coq-de-roche au cœur de l'intérieur.",
         "Do bem-te-vi presente em todo quintal de Paramaribo ao gavião-real e ao galo-da-serra no interior profundo."),
    "Reptiles": ("Reptiles", "Répteis"),
    "Snakes, lizards, caimans and turtles, including the sea turtles that nest on Suriname's beaches.":
        ("Serpents, lézards, caïmans et tortues, dont les tortues marines qui pondent sur les plages du Suriname.",
         "Serpentes, lagartos, jacarés e tartarugas, incluindo as tartarugas marinhas que desovam nas praias do Suriname."),
    "Amphibians": ("Amphibiens", "Anfíbios"),
    "Frogs, toads and caecilians, from the blue poison dart frog to the Surinam toad.":
        ("Grenouilles, crapauds et cécilies, du dendrobate azuré au pipa du Suriname.",
         "Rãs, sapos e cecílias, da rã-flecha-azul ao sapo-pipa."),
    "Fish": ("Poissons", "Peixes"),
    "Freshwater fish of the rivers and swamps, and the fish, sharks and rays of the Atlantic coast.":
        ("Poissons d'eau douce des fleuves et des marais, et poissons, requins et raies de la côte atlantique.",
         "Peixes de água doce dos rios e pântanos, e os peixes, tubarões e raias da costa atlântica."),
    "Insects": ("Insectes", "Insetos"),
    "Butterflies, beetles, ants, dragonflies, cicadas and thousands of other insects.":
        ("Papillons, coléoptères, fourmis, libellules, cigales et des milliers d'autres insectes.",
         "Borboletas, besouros, formigas, libélulas, cigarras e milhares de outros insetos."),
    "Spiders & scorpions": ("Araignées et scorpions", "Aranhas e escorpiões"),
    "Spiders, tarantulas, scorpions, harvestmen, ticks and mites.":
        ("Araignées, mygales, scorpions, opilions, tiques et acariens.",
         "Aranhas, caranguejeiras, escorpiões, opiliões, carrapatos e ácaros."),
    "Crabs & other crustaceans": ("Crabes et autres crustacés", "Caranguejos e outros crustáceos"),
    "Crabs, shrimps, prawns and their many small relatives in rivers, mangroves and the sea.":
        ("Crabes, crevettes et leurs nombreux petits cousins des fleuves, des mangroves et de la mer.",
         "Caranguejos, camarões e seus muitos parentes pequenos dos rios, manguezais e do mar."),
    "Snails, shells & other molluscs": ("Escargots, coquillages et autres mollusques", "Caramujos, conchas e outros moluscos"),
    "Land and freshwater snails, sea shells, mussels, squid and octopus.":
        ("Escargots terrestres et d'eau douce, coquillages marins, moules, calmars et pieuvres.",
         "Caramujos terrestres e de água doce, conchas marinhas, mexilhões, lulas e polvos."),
    "Other invertebrates": ("Autres invertébrés", "Outros invertebrados"),
    "Centipedes, millipedes, worms, corals, jellyfish, sponges, sea stars and more.":
        ("Scolopendres, mille-pattes, vers, coraux, méduses, éponges, étoiles de mer et bien d'autres.",
         "Lacraias, piolhos-de-cobra, vermes, corais, águas-vivas, esponjas, estrelas-do-mar e muito mais."),
    "Flowering plants": ("Plantes à fleurs", "Plantas com flores"),
    "Trees, shrubs, herbs, vines, grasses and water plants, grouped by plant family.":
        ("Arbres, arbustes, herbacées, lianes, graminées et plantes aquatiques, classés par famille.",
         "Árvores, arbustos, ervas, trepadeiras, gramíneas e plantas aquáticas, agrupadas por família."),
    "Orchids": ("Orchidées", "Orquídeas"),
    "One of the largest plant families in Suriname, most of them growing on trees in the rainforest.":
        ("L'une des plus grandes familles de plantes du Suriname ; la plupart poussent sur les arbres de la forêt tropicale.".replace(" ;", " ;"),
         "Uma das maiores famílias de plantas do Suriname; a maioria cresce sobre as árvores da floresta tropical."),
    "Palms": ("Palmiers", "Palmeiras"),
    "Awara, maripa, podosiri, troelie and every other palm, wild or planted.":
        ("Awara, maripa, podosiri, troelie et tous les autres palmiers, sauvages ou plantés.",
         "Awara, maripa, podosiri, troelie e todas as outras palmeiras, nativas ou plantadas."),
    "Ferns & clubmosses": ("Fougères et lycopodes", "Samambaias e licopódios"),
    "Tree ferns, climbing ferns, filmy ferns and clubmosses.":
        ("Fougères arborescentes, fougères grimpantes, hyménophyllacées et lycopodes.",
         "Samambaiaçus, samambaias trepadeiras, himenofiláceas e licopódios."),
    "Mosses & liverworts": ("Mousses et hépatiques", "Musgos e hepáticas"),
    "The small green carpets on tree trunks, rocks and the forest floor.":
        ("Les petits tapis verts sur les troncs, les rochers et le sol de la forêt.",
         "Os pequenos tapetes verdes nos troncos, nas rochas e no chão da floresta."),
    "Other plants & algae": ("Autres plantes et algues", "Outras plantas e algas"),
    "Conifers, cycads, Gnetum vines and green and red algae.":
        ("Conifères, cycas, lianes Gnetum et algues vertes et rouges.",
         "Coníferas, cicas, trepadeiras Gnetum e algas verdes e vermelhas."),
    "Fungi & lichens": ("Champignons et lichens", "Fungos e liquens"),
    "Mushrooms, bracket fungi, cup fungi and lichens.":
        ("Champignons à chapeau, polypores, pézizes et lichens.",
         "Cogumelos, orelhas-de-pau, fungos-taça e liquens."),
    # collections
    "Trees & timber": ("Arbres et bois", "Árvores e madeiras"),
    "Kankantrie, groenhart, basralocus, bolletrie and the other trees Surinamers know by name.":
        ("Kankantrie, groenhart, basralocus, bolletrie et les autres arbres que les Surinamais connaissent par leur nom.",
         "Kankantrie, groenhart, basralocus, bolletrie e as outras árvores que os surinameses conhecem pelo nome."),
    "Fruits, vegetables & crops": ("Fruits, légumes et cultures", "Frutas, legumes e cultivos"),
    "Mango, knippa, sopropo, cassave, tayer: the plants on Surinamese plates and in market stalls.":
        ("Mangue, knippa, sopropo, manioc, tayer : les plantes des assiettes et des étals surinamais.",
         "Manga, knippa, sopropo, mandioca, tayer: as plantas dos pratos e das bancas de feira do Suriname."),
    "Known by a Sranan name": ("Connus sous un nom sranan", "Conhecidos por um nome em sranan"),
    "Animals and plants that have their own name in Sranan Tongo, linked to our dictionary.":
        ("Animaux et plantes qui ont leur propre nom en sranan tongo, avec un lien vers notre dictionnaire.",
         "Animais e plantas que têm nome próprio em sranan tongo, com link para o nosso dicionário."),
    "Found only in Suriname": ("Présents uniquement au Suriname", "Encontrados só no Suriname"),
    "Species and subspecies known from Suriname and nowhere else, after the National Zoological Collection of Suriname.":
        ("Espèces et sous-espèces connues au Suriname et nulle part ailleurs, d'après la Collection zoologique nationale du Suriname.",
         "Espécies e subespécies conhecidas no Suriname e em nenhum outro lugar, segundo a Coleção Zoológica Nacional do Suriname."),
    "Threatened species": ("Espèces menacées", "Espécies ameaçadas"),
    "Species rated Vulnerable, Endangered or Critically Endangered on the IUCN Red List.":
        ("Espèces classées Vulnérable, En danger ou En danger critique sur la Liste rouge de l'UICN.",
         "Espécies classificadas como Vulnerável, Em perigo ou Criticamente em perigo na Lista Vermelha da IUCN."),
    "Introduced & invasive": ("Introduites et envahissantes", "Introduzidas e invasoras"),
    "Species brought to Suriname by people, on purpose or by accident.":
        ("Espèces apportées au Suriname par l'homme, volontairement ou par accident.",
         "Espécies trazidas ao Suriname pelo ser humano, de propósito ou por acidente."),
    # subgroups: mammals
    "Monkeys": ("Singes", "Macacos"),
    "Cats, otters & other carnivores": ("Félins, loutres et autres carnivores", "Felinos, lontras e outros carnívoros"),
    "Sloths, anteaters & armadillos": ("Paresseux, fourmiliers et tatous", "Preguiças, tamanduás e tatus"),
    "Dolphins & whales": ("Dauphins et baleines", "Golfinhos e baleias"),
    "Deer, peccaries & tapir": ("Cerfs, pécaris et tapir", "Veados, porcos-do-mato e anta"),
    "Rodents": ("Rongeurs", "Roedores"),
    "Bats": ("Chauves-souris", "Morcegos"),
    "Opossums": ("Opossums", "Gambás"),
    "Manatee & other mammals": ("Lamantin et autres mammifères", "Peixe-boi e outros mamíferos"),
    # birds
    "Parrots & macaws": ("Perroquets et aras", "Papagaios e araras"),
    "Toucans, woodpeckers & jacamars": ("Toucans, pics et jacamars", "Tucanos, pica-paus e ariramba"),
    "Hummingbirds & swifts": ("Colibris et martinets", "Beija-flores e andorinhões"),
    "Birds of prey & vultures": ("Rapaces et vautours", "Aves de rapina e urubus"),
    "Owls": ("Chouettes et hiboux", "Corujas"),
    "Herons, ibises & storks": ("Hérons, ibis et cigognes", "Garças, íbis e cegonhas"),
    "Shorebirds, gulls & terns": ("Limicoles, goélands et sternes", "Aves limícolas, gaivotas e trinta-réis"),
    "Seabirds & cormorants": ("Oiseaux marins et cormorans", "Aves marinhas e biguás"),
    "Ducks & screamers": ("Canards et kamichis", "Patos e tachãs"),
    "Rails, limpkin & sunbittern": ("Râles, courlan et caurale", "Saracuras, carão e pavãozinho-do-pará"),
    "Guans, curassows & quails": ("Pénélopes, hoccos et colins", "Jacus, mutuns e uru"),
    "Tinamous": ("Tinamous", "Inhambus"),
    "Pigeons & doves": ("Pigeons et colombes", "Pombos e rolinhas"),
    "Cuckoos, anis & hoatzin": ("Coucous, anis et hoazin", "Cucos, anus e cigana"),
    "Nightjars, potoos & oilbird": ("Engoulevents, ibijaux et guácharo", "Bacuraus, urutaus e guácharo"),
    "Kingfishers, motmots & trogons": ("Martins-pêcheurs, motmots et trogons", "Martins-pescadores, udus e surucuás"),
    "Songbirds & other perching birds": ("Passereaux", "Pássaros canoros e outros passeriformes"),
    "Other birds": ("Autres oiseaux", "Outras aves"),
    # reptiles / amphibians / fish
    "Snakes": ("Serpents", "Serpentes"),
    "Turtles & tortoises": ("Tortues", "Tartarugas, cágados e jabutis"),
    "Caimans": ("Caïmans", "Jacarés"),
    "Lizards & worm lizards": ("Lézards et amphisbènes", "Lagartos e cobras-de-duas-cabeças"),
    "Frogs & toads": ("Grenouilles et crapauds", "Rãs e sapos"),
    "Caecilians & salamanders": ("Cécilies et salamandres", "Cecílias e salamandras"),
    "Characins, piranhas & tetras": ("Characins, piranhas et tétras", "Caracídeos, piranhas e tetras"),
    "Catfish": ("Poissons-chats", "Bagres"),
    "Cichlids": ("Cichlidés", "Ciclídeos"),
    "Knifefish & electric eel": ("Poissons-couteaux et anguille électrique", "Peixes-faca e poraquê"),
    "Killifish, livebearers & four-eyed fish": ("Killis, poissons vivipares et anableps", "Killifish, peixes vivíparos e tralhotos"),
    "Sharks & rays": ("Requins et raies", "Tubarões e raias"),
    "Other fish (coast and sea)": ("Autres poissons (côte et mer)", "Outros peixes (costa e mar)"),
    # insects / arachnids / others
    "Butterflies & moths": ("Papillons de jour et de nuit", "Borboletas e mariposas"),
    "Beetles": ("Coléoptères", "Besouros"),
    "Ants, bees & wasps": ("Fourmis, abeilles et guêpes", "Formigas, abelhas e vespas"),
    "Dragonflies & damselflies": ("Libellules et demoiselles", "Libélulas e donzelinhas"),
    "Grasshoppers & crickets": ("Criquets, sauterelles et grillons", "Gafanhotos e grilos"),
    "True bugs, cicadas & leafhoppers": ("Punaises, cigales et cicadelles", "Percevejos, cigarras e cigarrinhas"),
    "Flies & mosquitoes": ("Mouches et moustiques", "Moscas e mosquitos"),
    "Mantises & stick insects": ("Mantes et phasmes", "Louva-a-deus e bichos-pau"),
    "Cockroaches & termites": ("Blattes et termites", "Baratas e cupins"),
    "Other insects": ("Autres insectes", "Outros insetos"),
    "Spiders & tarantulas": ("Araignées et mygales", "Aranhas e caranguejeiras"),
    "Scorpions": ("Scorpions", "Escorpiões"),
    "Harvestmen": ("Opilions", "Opiliões"),
    "Ticks & mites": ("Tiques et acariens", "Carrapatos e ácaros"),
    "Whip spiders & other arachnids": ("Amblypyges et autres arachnides", "Amblipígios e outros aracnídeos"),
    "Crabs": ("Crabes", "Caranguejos"),
    "Shrimps, prawns & lobsters": ("Crevettes et homards", "Camarões e lagostas"),
    "Other crustaceans": ("Autres crustacés", "Outros crustáceos"),
    "Snails & slugs": ("Escargots et limaces", "Caramujos e lesmas"),
    "Clams, mussels & oysters": ("Palourdes, moules et huîtres", "Mariscos, mexilhões e ostras"),
    "Squid & octopus": ("Calmars et pieuvres", "Lulas e polvos"),
    "Other molluscs": ("Autres mollusques", "Outros moluscos"),
    "Centipedes & millipedes": ("Scolopendres et mille-pattes", "Lacraias e piolhos-de-cobra"),
    "Worms & leeches": ("Vers et sangsues", "Vermes e sanguessugas"),
    "Corals, anemones & jellyfish": ("Coraux, anémones et méduses", "Corais, anêmonas e águas-vivas"),
    "Sea stars, urchins & sea cucumbers": ("Étoiles de mer, oursins et concombres de mer", "Estrelas-do-mar, ouriços e pepinos-do-mar"),
    "Sponges": ("Éponges", "Esponjas"),
    "Other small animals": ("Autres petits animaux", "Outros pequenos animais"),
    # plants / fungi subgroups
    "Ferns": ("Fougères", "Samambaias"),
    "Clubmosses & spikemosses": ("Lycopodes et sélaginelles", "Licopódios e selaginelas"),
    "Mosses": ("Mousses", "Musgos"),
    "Liverworts & hornworts": ("Hépatiques et anthocérotes", "Hepáticas e antóceros"),
    "Conifers, cycads & Gnetum": ("Conifères, cycas et Gnetum", "Coníferas, cicas e Gnetum"),
    "Green & red algae": ("Algues vertes et rouges", "Algas verdes e vermelhas"),
    "Mushrooms & bracket fungi": ("Champignons à chapeau et polypores", "Cogumelos e orelhas-de-pau"),
    "Lichens": ("Lichens", "Liquens"),
    "Cup fungi, moulds & other fungi": ("Pézizes, moisissures et autres champignons", "Fungos-taça, bolores e outros fungos"),
    "All other plant families": ("Toutes les autres familles", "Todas as outras famílias"),
    # language names
    "English": ("Anglais", "Inglês"),
    "Dutch": ("Néerlandais", "Neerlandês"),
    "Spanish": ("Espagnol", "Espanhol"),
    "Chinese": ("Chinois", "Chinês"),
    "French": ("Français", "Francês"),
    "Portuguese": ("Portugais", "Português"),
    # interface
    "Flora & Fauna": ("Faune et flore", "Fauna e flora"),
    "Flora & Fauna of Suriname": ("Faune et flore du Suriname", "Fauna e flora do Suriname"),
    "Home": ("Accueil", "Início"),
    "Search any animal or plant, in any language": ("Cherchez un animal ou une plante, dans n'importe quelle langue",
                                                    "Busque qualquer animal ou planta, em qualquer idioma"),
    "Search species": ("Chercher une espèce", "Buscar espécies"),
    "Try jaguar, kankantri, pakira or Ceiba pentandra.": ("Essayez jaguar, kankantri, pakira ou Ceiba pentandra.",
                                                         "Experimente jaguar, kankantri, pakira ou Ceiba pentandra."),
    "No species match your search.": ("Aucune espèce ne correspond à votre recherche.",
                                      "Nenhuma espécie corresponde à sua busca."),
    "Loading…": ("Chargement…", "Carregando…"),
    "Close": ("Fermer", "Fechar"),
    "Menu": ("Menu", "Menu"),
    "All groups": ("Tous les groupes", "Todos os grupos"),
    "Learn": ("Découvrir", "Aprender"),
    "Every animal, plant and fungus recorded in Suriname, with its name in English, Dutch, Spanish, Chinese, Sranan Tongo and Latin.":
        ("Tous les animaux, plantes et champignons observés au Suriname, avec leur nom en anglais, néerlandais, espagnol, chinois, sranan tongo et latin.",
         "Todos os animais, plantas e fungos registrados no Suriname, com seus nomes em inglês, neerlandês, espanhol, chinês, sranan tongo e latim."),
    "species recorded": ("espèces observées", "espécies registradas"),
    "species profiles": ("fiches d'espèces", "fichas de espécies"),
    "Sranan names": ("noms en sranan", "nomes em sranan"),
    "Plants & fungi": ("Plantes et champignons", "Plantas e fungos"),
    "Collections": ("Collections", "Coleções"),
    "Most observed in Suriname": ("Les plus observées au Suriname", "As mais observadas no Suriname"),
    "Ranked by observations shared on iNaturalist from Suriname.": (
        "Classées selon les observations partagées sur iNaturalist depuis le Suriname.",
        "Classificadas pelas observações do Suriname compartilhadas no iNaturalist."),
    "See all": ("Tout voir", "Ver todos"),
    "species": ("espèces", "espécies"),
    "profiles": ("fiches", "fichas"),
    "Also on the checklist": ("Également sur la liste", "Também na lista"),
    "Recorded in Suriname, but there is not enough reliable information yet for a full profile.": (
        "Observées au Suriname, mais les informations fiables manquent encore pour une fiche complète.",
        "Registradas no Suriname, mas ainda não há informações confiáveis suficientes para uma ficha completa."),
    "Filter this list": ("Filtrer cette liste", "Filtrar esta lista"),
    "Most observed": ("Les plus observées", "Mais observadas"),
    "Name A–Z": ("Nom A–Z", "Nome A–Z"),
    "Scientific name": ("Nom scientifique", "Nome científico"),
    "Groups": ("Groupes", "Grupos"),
    "Records": ("Données", "Registros"),
    "Family": ("Famille", "Família"),
    "Names": ("Noms", "Nomes"),
    "Also recorded as": ("Également enregistrée sous", "Também registrada como"),
    "Local names": ("Noms locaux", "Nomes locais"),
    "general name for the group": ("nom générique du groupe", "nome genérico do grupo"),
    "About": ("À propos", "Sobre"),
    "About this species": ("À propos de cette espèce", "Sobre esta espécie"),
    "Read more on Wikipedia": ("En savoir plus sur Wikipédia", "Leia mais na Wikipédia"),
    "Text: Wikipedia, CC BY-SA 4.0": ("Texte : Wikipédia, CC BY-SA 4.0", "Texto: Wikipédia, CC BY-SA 4.0"),
    "(in English)": ("(en anglais)", "(em inglês)"),
    "In Suriname": ("Au Suriname", "No Suriname"),
    "Records in Suriname": ("Données au Suriname", "Registros no Suriname"),
    "iNaturalist observations": ("Observations iNaturalist", "Observações no iNaturalist"),
    "First record": ("Première donnée", "Primeiro registro"),
    "Latest record": ("Dernière donnée", "Registro mais recente"),
    "Where it has been recorded": ("Où elle a été observée", "Onde foi registrada"),
    "Districts with at least one record that has coordinates. Shaded districts have records.": (
        "Districts comptant au moins une donnée géolocalisée. Les districts colorés ont des données.",
        "Distritos com pelo menos um registro com coordenadas. Os distritos sombreados têm registros."),
    "Records by month": ("Données par mois", "Registros por mês"),
    "All years combined.": ("Toutes années confondues.", "Todos os anos somados."),
    "Status": ("Statut", "Situação"),
    "IUCN Red List": ("Liste rouge de l'UICN", "Lista Vermelha da IUCN"),
    "Endemic to Suriname": ("Endémique du Suriname", "Endêmica do Suriname"),
    "Introduced by people": ("Introduite par l'homme", "Introduzida pelo ser humano"),
    "On Suriname's list of threatened fauna": ("Sur la liste de la faune menacée du Suriname",
                                               "Na lista da fauna ameaçada do Suriname"),
    "Native": ("Indigène", "Nativa"),
    "Classification": ("Classification", "Classificação"),
    "Kingdom": ("Règne", "Reino"),
    "Phylum": ("Embranchement", "Filo"),
    "Class": ("Classe", "Classe"),
    "Order": ("Ordre", "Ordem"),
    "Genus": ("Genre", "Gênero"),
    "Related species in Suriname": ("Espèces apparentées au Suriname", "Espécies relacionadas no Suriname"),
    "Sources & credits": ("Sources et crédits", "Fontes e créditos"),
    "Photo": ("Photo", "Foto"),
    "No photo yet": ("Pas encore de photo", "Ainda sem foto"),
    "in our Sranan Tongo dictionary": ("dans notre dictionnaire sranan tongo", "no nosso dicionário de sranan tongo"),
    "Records: GBIF.org occurrence data for Suriname": ("Données : occurrences GBIF.org pour le Suriname",
                                                       "Registros: dados de ocorrência do GBIF.org para o Suriname"),
    "Observations and names: iNaturalist": ("Observations et noms : iNaturalist", "Observações e nomes: iNaturalist"),
    "Names in other languages: Wikidata": ("Noms dans d'autres langues : Wikidata", "Nomes em outros idiomas: Wikidata"),
    "Sranan names: Explore Suriname Sranan Tongo dictionary": (
        "Noms en sranan : dictionnaire sranan tongo d'Explore Suriname",
        "Nomes em sranan: dicionário de sranan tongo do Explore Suriname"),
    "Suriname status: National Zoological Collection of Suriname (NZCS) checklists": (
        "Statut au Suriname : listes de la Collection zoologique nationale du Suriname (NZCS)",
        "Situação no Suriname: listas da Coleção Zoológica Nacional do Suriname (NZCS)"),
    "Spotted a mistake or know another local name? Tell us.": (
        "Vous avez repéré une erreur ou connaissez un autre nom local ? Dites-le-nous.",
        "Encontrou um erro ou conhece outro nome local? Conte para a gente."),
    "Data updated": ("Données mises à jour", "Dados atualizados"),
    "About this guide": ("À propos de ce guide", "Sobre este guia"),
    "How we compile the Flora & Fauna of Suriname, where the information comes from and how you can help.": (
        "Comment nous réalisons la Faune et flore du Suriname, d'où viennent les informations et comment vous pouvez aider.",
        "Como montamos a Fauna e flora do Suriname, de onde vêm as informações e como você pode ajudar."),
    "A free guide by Explore Suriname. Names, records and photos come from open biodiversity data; every source is credited on the page where it is used.": (
        "Un guide gratuit d'Explore Suriname. Les noms, données et photos proviennent de données ouvertes sur la biodiversité ; chaque source est citée sur la page où elle est utilisée.",
        "Um guia gratuito do Explore Suriname. Nomes, registros e fotos vêm de dados abertos de biodiversidade; cada fonte é creditada na página em que é usada."),
    "Skip to content": ("Aller au contenu", "Pular para o conteúdo"),
    "Explore Suriname": ("Explore Suriname", "Explore Suriname"),
    "Flora & Fauna of Suriname: Animals, Plants and their Names": (
        "Faune et flore du Suriname : animaux, plantes et leurs noms",
        "Fauna e flora do Suriname: animais, plantas e seus nomes"),
    "About the Flora & Fauna of Suriname guide": ("À propos du guide Faune et flore du Suriname",
                                                  "Sobre o guia Fauna e flora do Suriname"),
    "Things to Do": ("À faire", "O que fazer"),
    "Events & Festivals": ("Événements et fêtes", "Eventos e festas"),
    "About Suriname": ("À propos du Suriname", "Sobre o Suriname"),
    "History Timeline": ("Frise chronologique", "Linha do tempo"),
    "Sranan Dictionary": ("Dictionnaire sranan", "Dicionário de sranan"),
    "Visitor Guide": ("Guide du visiteur", "Guia do visitante"),
    # plant families
    "Legumes: pea and bean family": ("Fabacées : famille des pois et des haricots", "Fabáceas: família do feijão e da ervilha"),
    "Coffee family": ("Rubiacées (famille du café)", "Rubiáceas (família do café)"),
    "Melastomes": ("Mélastomatacées", "Melastomatáceas"),
    "Grasses & bamboos": ("Graminées et bambous", "Gramíneas e bambus"),
    "Sedges": ("Cypéracées", "Ciperáceas"),
    "Bromeliads & pineapple": ("Broméliacées et ananas", "Bromélias e abacaxi"),
    "Aroids: philodendrons & tayer": ("Aracées : philodendrons et tayer", "Aráceas: filodendros e tayer"),
    "Myrtle family: guava & Suriname cherry": ("Myrtacées : goyave et cerise de Cayenne", "Mirtáceas: goiaba e pitanga"),
    "Spurge family: cassava & rubber": ("Euphorbiacées : manioc et hévéa", "Euforbiáceas: mandioca e seringueira"),
    "Mallow family: kapok, cacao & okra": ("Malvacées : fromager, cacao et gombo", "Malváceas: sumaúma, cacau e quiabo"),
    "Custard-apple family: soursop": ("Annonacées : corossol", "Anonáceas: graviola"),
    "Laurel family: avocado & wana": ("Lauracées : avocat et wana", "Lauráceas: abacate e wana"),
    "Sapote family: balata & star apple": ("Sapotacées : balata et pomme de lait", "Sapotáceas: balatá e caimito"),
    "Cocoplum family": ("Chrysobalanacées", "Crisobalanáceas"),
    "Brazil nut family: cannonball tree": ("Lécythidacées : arbre à boulets de canon", "Lecitidáceas: abricó-de-macaco"),
    "Pepper family: Piper & Peperomia": ("Pipéracées : Piper et Peperomia", "Piperáceas: Piper e Peperomia"),
    "Daisy family": ("Astéracées", "Asteráceas"),
    "Dogbane family": ("Apocynacées", "Apocináceas"),
    "Trumpet-tree family: groenhart & calabash": ("Bignoniacées : groenhart et calebassier", "Bignoniáceas: groenhart e cabaça"),
    "Fig & mulberry family": ("Moracées : figuiers et mûriers", "Moráceas: figueiras e amoreiras"),
    "Nightshade family: peppers & antroewa": ("Solanacées : piments et antroewa", "Solanáceas: pimentas e antroewa"),
    "Gingers, heliconias & bananas": ("Gingembres, héliconias et bananiers", "Gengibres, helicônias e bananeiras"),
    "Passionflowers & markoesa": ("Passiflores et markoesa", "Maracujás e markoesa"),
    "Gesneriads": ("Gesnériacées", "Gesneriáceas"),
    "Acanthus family": ("Acanthacées", "Acantáceas"),
    "Bladderworts": ("Utriculaires", "Utriculárias"),
    "Morning glories & sweet potato": ("Convolvulacées : liserons et patate douce", "Convolvuláceas: ipomeias e batata-doce"),
    "Gourd family: sopropo & pumpkin": ("Cucurbitacées : sopropo et potiron", "Cucurbitáceas: sopropo e abóbora"),
    "Water lilies": ("Nymphéacées", "Ninfeáceas"),
}

# Month abbreviations (U["months"] in flora_fauna_pages.py, built from tuples)
MONTHS_FR = ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."]
MONTHS_PT = ["jan.", "fev.", "mar.", "abr.", "mai.", "jun.", "jul.", "ago.", "set.", "out.", "nov.", "dez."]
